language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t semie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true semie/react-test yarn test

after_success:
  - docker build -t semie/multi-client ./client
  - docker build -t semie/multi-nginx ./nginx
  - docker build -t semie/multi-server ./server
  - docker build -t semie/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push semie/multi-client
  - docker push semie/multi-nginx
  - docker push semie/multi-server
  - docker push semie/multi-worker
